### PR TITLE
LRQA-41624 Support poshi script syntax for the new 'Table' related attributes (var & for elements) 

### PR DESCRIPTION
**Pull request by pyoo47**
https://issues.liferay.com/browse/LRQA-41624

@yichenroy

Pull request tested here https://github.com/pyoo47/com-liferay-poshi-runner/pull/104 (PASSED)

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@pyoo47 @kenjiheigel can we turn

```
		for (var row : table "${rowsHashTable}") {
			TableEcho.echoTwoVars(
				v0 = "${row.hash('project_id')}",
				v1 = "${row.hash('status')}"
			);
		}
		var RawTable rawTable = new RawTable("${table}");
```

into

```
		for (var row : table "${rowsHashTable}") {
			TableEcho.echoTwoVars(
				v0 = "${row.hash('project_id')}",
				v1 = "${row.hash('status')}"
			);
		}

		var RawTable rawTable = new RawTable("${table}");
```

Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/com-liferay-poshi-runner/compare/8a92f342a1...03678eca7c

**Comment by brianchandotcom** [comment]
@pyoo47 published.

**Comment by kenjiheigel** [comment]
@brianchandotcom, yeah I can update the generation to have the new line. I made a ticket for it here: https://issues.liferay.com/browse/LRQA-41708

I'm currently updating/consolidating a lot of syntax validation and syntax generation right now, so I'll update it after those changes.

**Pull request closed without merging**
