### PR TITLE
LRQA-45588 Validate for missing commas between variables in functions and macros

### PR DESCRIPTION
**Pull request by pyoo47**
https://issues.liferay.com/browse/LRQA-45588

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/com-liferay-poshi-runner/compare/0b55092adb...1edadf5edd

**Comment by brianchandotcom** [comment]
See 1edadf5edd73fc549bf913f3384482371deb923e Thx.

**Comment by brianchandotcom** [comment]
Woops, I meant see ba91046ead74971a83e09f0c27ffa33d260fb421 @pyoo47

**Pull request closed without merging**
