### PR TITLE
LRCI-683 Fix waitFor* logic

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRCI-683

### CODE REVIEW

**Comment by kenjiheigel** [comment]
cc-ing: @pyoo47

**Comment by kenjiheigel** [comment]
ci:test

**Comment by kenjiheigel** [comment]
I think the issue is related to the way the subrepository tester works in relation to the *-private changes in liferay-portal. @yichenroy, @pyoo47

#### Error Message
```
Missing modules/dxp/apps/portal-search-tuning/build.gradle
```
#### Stacktrace
````
junit.framework.AssertionFailedError: Missing modules/dxp/apps/portal-search-tuning/build.gradle
	at com.liferay.portal.modules.util.ModulesStructureTestUtil.read(ModulesStructureTestUtil.java:134)
	at com.liferay.portal.modules.ModulesStructureTest._testEquals(ModulesStructureTest.java:951)
	at com.liferay.portal.modules.ModulesStructureTest.access$300(ModulesStructureTest.java:65)
	at com.liferay.portal.modules.ModulesStructureTest$1.preVisitDirectory(ModulesStructureTest.java:195)
	at com.liferay.portal.modules.ModulesStructureTest$1.preVisitDirectory(ModulesStructureTest.java:121)
	at java.nio.file.Files.walkFileTree(Files.java:2677)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at com.liferay.portal.modules.ModulesStructureTest.testScanBuildScripts(ModulesStructureTest.java:119)
```

**Comment by yichenroy** [comment]
ci:test:validation

**Comment by yichenroy** [comment]
@kenjiheigel 
The issue should be resolved after the next master stable merge, there was a fix pushed onto Brian's origin 3 hours ago:
https://github.com/brianchandotcom/liferay-portal/commit/18b81d649c7cddbc144497dabee4262c7f6bf0e1

cc @pyoo47

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/com-liferay-poshi-runner/compare/ffcf12c520...5b705d9206

**Pull request closed without merging**
