### PR TITLE
LRQA-35911 SF

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRQA-35911

Review from https://github.com/michaelhashimoto/com-liferay-poshi-runner/pull/11

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test

**Comment by michaelhashimoto** [comment]
@brianchandotcom - It passes on this pull request:
https://github.com/michaelhashimoto/com-liferay-poshi-runner/pull/11

**Comment by brianchandotcom** [comment]
@michaelhashimoto this will make it so poshi can't run outside the portal since GetterUtil doesn't exist there.

@hhuijser This module needs to work outside the portal. What can we do? Thx.

not merging.

**Comment by michaelhashimoto** [comment]
@brianchandotcom - Actually we have our own "GetterUtil".  I think when we first made poshi runner into a module, you told us to just copy "GetterUtil", and eventually we would move it into a jar that we can just include within poshi runner.

So this would actually work for now.  But we were wondering about how to handle it in the future.

Thanks!

**Comment by michaelhashimoto** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/com-liferay-poshi-runner/compare/c078b913f2...b8344c4436

**Pull request closed without merging**
