### PR TITLE
LRQA-35687 PoshiElements: Allow class loading to work whether in a jar or local file system using guava

### PR DESCRIPTION
**Pull request by pyoo47**
https://issues.liferay.com/browse/LRQA-35687

Please publish after merging

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/com-liferay-poshi-runner/compare/2e60c372d3...c078b913f2

**Comment by brianchandotcom** [comment]
Not merging SF commit as it'll force poshi runner to not work outside the portal. I already pinged @hhuijser about this.

**Comment by hhuijser** [comment]
@brianchandotcom Looks like poshi is using its own GetterUtil?

**Pull request closed without merging**
